# Generated by Django 3.1.2 on 2020-11-11 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_reply_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='post_timestamp',
            new_name='reply_timestamp',
        ),
    ]
