# Generated by Django 3.1.2 on 2020-11-20 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201117_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='t_s',
            field=models.CharField(choices=[('S', 'student'), ('T', 'teacher')], default='S', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
